JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        DBApp.java\
        DBAppTest.java \
        HardDrive.java \
        Page.java \
	Reflector.java \
	SearchResult.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
        $(RM) *.class